// src/components/Layout/Header.vue
<template>
  <header class="flex justify-center h-24 bg-grey-700 backdrop-blur fixed w-full z-50">
    <div class="flex items-center max-w-[1540px] w-full justify-between mx-8 md:mx-6 lg:mx-10">
      <img alt="Logo" src="../../assets/reduceLogo.svg" class="w-[70px]" />
      <ul class="cursor-pointer hidden lg:gap-x-2 md:flex items-center justify-around">
        <li class="navBar-text">Sobre</li>
        <li class="navBar-text">História</li>
        <li class="navBar-text">Habilidades</li>
        <li class="navBar-text">Projetos</li>
      </ul>
      <div class="gap-x-2 md:flex gap-y-2 hidden lg:px-0 items-center justify-between flex-row xl:gap-x-8 lg:gap-x-4">
        <div :class="[
          'text-white py-2 px-3 cursor-pointer rounded-lg duration-200 hover:bg-grey-500 flex items-center justify-between border-0', 
          'md:hover:text-blue-500 lg:hover:text-white lg:text-white lg:px-4 lg:py-3 lg:w-48 lg:border lg:border-grey-300 md:text-grey-100'
          ]"
        >
          <span class="hidden lg:inline">Inglês</span>
          <Languages :size="22" />
        </div>
        <div class="bg-grey-300 h-[45px] w-px lg:ml-3"></div>
        <div class="flex items-center justify-between text-white lg:gap-x-2">
          <Links size="xl" />
        </div>
      </div>
      <HeaderWrapper class-name="md:hidden" />
    </div>
  </header>
</template>

<script setup lang="ts">
  import { Languages } from 'lucide-vue-next';
  import HeaderWrapper from '../HeaderWrapper.vue';
  import Links from '../Links.vue';
</script>

// src/components/Layout/header.tsx
import { Languages, Sun } from "lucide-react";
import Logo from "../../assets/reduceLogo.svg";

const Header = () => {
	return (
		<div className="flex justify-center py-3 px-6 border-b border-neutral-800 bg-neutral-900/60 backdrop-blur-md fixed top-0 left-0 w-full">
			<header className="flex justify-between w-full max-w-6xl">
				<img src={Logo} alt="Logo" className="w-12" />
				<nav className="flex items-center">
					<ul className="flex items-center gap-4">
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Sobre mim
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Stacks
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Projetos
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Certificados
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Contato
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-full flex duration-300 ease-in-out">
							<button type="button" className="px-2 py-2 cursor-pointer">
								<Sun color="#fff" size={14} />
							</button>
						</li>
						<li className="hover:bg-neutral-800 rounded-full flex duration-300 ease-in-out">
							<button type="button" className="px-2 py-2 cursor-pointer">
								<Languages color="#fff" size={14} />
							</button>
						</li>
					</ul>
				</nav>
			</header>
		</div>
	);
};

export default Header;
