// src/components/Header.vue
<script setup lang="ts">
  import { Languages } from 'lucide-vue-next';
</script>

<template>
  <header class="flex justify-center h-[10vh] bg-grey-600 backdrop-blur fixed w-full z-50 md:bg-grey-600/80">
    <div class="flex items-center max-w-[1540px] w-full justify-between mx-6 lg:mx-10">
      <img alt="Logo" class="w-[200px] xl:w-[250px]" />
      <ul class="text-white cursor-pointer space-x-2 flex items-center justify-around">
        <li class="duration-200 hover:bg-grey-700 py-2 px-3 rounded-lg">Sobre</li>
        <li class="duration-200 hover:bg-grey-700 py-2 px-3 rounded-lg">História</li>
        <li class="duration-200 hover:bg-grey-700 py-2 px-3 rounded-lg">Habilidades</li>
        <li class="duration-200 hover:bg-grey-700 py-2 px-3 rounded-lg">Projetos</li>
      </ul>
      <div class="gap-x-2 flex items-center justify-between">
        <div class="text-white w-48 border border-grey-100 px-4 py-3 rounded-lg duration-200 hover:bg-grey-700 flex items-center justify-between">
          <span>Inglês</span>
          <Languages :size="22" />
        </div>
      </div>
    </div>
  </header>
</template>

<style scoped>

</style>

// src/components/Layout/header.tsx
import { Languages, Sun } from "lucide-react";
import Logo from "../../assets/reduceLogo.svg";

const Header = () => {
	return (
		<div className="flex justify-center py-3 px-6 border-b border-neutral-800 bg-neutral-900/60 backdrop-blur-md fixed top-0 left-0 w-full">
			<header className="flex justify-between w-full max-w-6xl">
				<img src={Logo} alt="Logo" className="w-12" />
				<nav className="flex items-center">
					<ul className="flex items-center gap-4">
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Sobre mim
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Stacks
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Projetos
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Certificados
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-lg flex duration-300 ease-in-out">
							<a href="#" className="text-white px-3 py-1.5 text-sm">
								Contato
							</a>
						</li>
						<li className="hover:bg-neutral-800 rounded-full flex duration-300 ease-in-out">
							<button type="button" className="px-2 py-2 cursor-pointer">
								<Sun color="#fff" size={14} />
							</button>
						</li>
						<li className="hover:bg-neutral-800 rounded-full flex duration-300 ease-in-out">
							<button type="button" className="px-2 py-2 cursor-pointer">
								<Languages color="#fff" size={14} />
							</button>
						</li>
					</ul>
				</nav>
			</header>
		</div>
	);
};

export default Header;
