// src/components/project-card.tsx
import clsx from "clsx";
import { ProjectsProps } from "../types/type";
import Button from "./button";
import { ExternalLink } from "lucide-react";

type Props = ProjectsProps & {
	reverse?: boolean;
};

const ProjectCard = ({
	description,
	image,
	name,
	skills,
	additionalLink,
	repo,
	website,
	reverse,
}: Props) => {
	return (
		<div
			className={clsx(
				"flex items-center gap-x-12 h-[320px]",
				reverse && "flex-row-reverse",
			)}
		>
			<img
				className="min-w-[570px] h-full relative border-2 border-neutral-800 object-cover rounded-lg hover:opacity-70 duration-300 ease-in-out"
				src={image}
				alt="Imagem do projeto"
			/>
			<div className="flex flex-col gap-y-5">
				<div className="flex items-center flex-col gap-y-1">
					<h1 className="text-lg text-white">{name}</h1>
					<div className="flex gap-x-1">
						{skills.map((skill, index) => (
							<span
								className="text-white bg-neutral-900 border border-neutral-800 rounded-md text-xs px-2 py-0.5"
								key={`${skill}${index}`}
							>
								{skill}
							</span>
						))}
					</div>
				</div>
				<p className="text-neutral-400 text-center text-sm">{description}</p>
				<div className="flex gap-x-3">
					{website && (
						<Button
							icon={<ExternalLink size={16} color="#fff" />}
							href={website}
							className="flex-1 flex justify-center gap-x-2 items-center text-center"
							theme="primary"
						>
							Visitar projeto
						</Button>
					)}
					{additionalLink && (
						<Button
							icon={<ExternalLink size={16} color="#fff" />}
							href={additionalLink}
							className="flex-1 flex justify-center gap-x-2 items-center text-center"
							theme="outline"
						>
							Link adicional
						</Button>
					)}
					{repo && (
						<Button
							icon={<ExternalLink size={16} color="#fff" />}
							href={repo}
							className="flex-1 flex justify-center gap-x-2 items-center text-center"
							theme="outline"
						>
							Repósitorio
						</Button>
					)}
				</div>
			</div>
		</div>
	);
};

export default ProjectCard;

// src/components/projectCard.vue
<template>
  <div class="bg-gradient-to-tl from-grey-800 shadow-lg to-grey-600 min-h-[730px] rounded-md flex flex-col">
    <a
      :href="website"
      target="_blank"
    >
      <img
        :src="image"
        :alt="description"
        class="w-full h-80 rounded-t-md object-cover duration-200 hover:opacity-50"
      >
    </a>
    <div class="flex flex-col flex-1 gap-y-6 px-6 py-8 justify-center">
      <div class="flex flex-col items-center gap-y-2">
        <h1 class="text-white text-2xl font-montserrat">
          {{ name }}
        </h1>
        <p class="text-white text-center">
          {{ description }}
        </p>
      </div>
      <div class="flex items-center gap-6 flex-wrap">
        <span
          v-for="(skill, index) in skills"
          :key="index"
          class="py-2 px-4 bg-grey-500 text-white rounded-md duration-200 cursor-default hover:bg-grey-400"
        >
          {{ skill }}
        </span>
      </div>
      <div class="flex flex-col justify-around items-center gap-y-6 px-6">
        <ButtonComponent
          title="Link para redirecionar ao repositório no GitHub"
          class-name="w-4/5"
          :href="repo"
        >
          Repositório
        </ButtonComponent>
        <ButtonComponent
          class-name="w-4/5"
          :href="website"
        >
          Site
        </ButtonComponent>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import ButtonComponent from './buttonComponent.vue'

interface ProjectProps {
  website: string
  description: string
  image: string
  name: string
  skills: string[]
  repo: string | undefined
}

const { description, image, name, repo, skills, website } = defineProps<ProjectProps>()
</script>
