// src/App.vue
<script setup lang="ts">
import FooterBar from './components/Layout/footerBar.vue'
import HeaderBar from './components/Layout/headerBar.vue'
import AboutSection from './components/Section/aboutSection.vue'
import HistorySection from './components/Section/historySection.vue'
import ProjectsSection from './components/Section/projectsSection.vue'
import SkillsSection from './components/Section/skillsSection.vue'
</script>

<template>
  <HeaderBar />
  <main class="flex flex-col gap-y-36">
    <AboutSection />
    <HistorySection />
    <SkillsSection />
    <ProjectsSection />
  </main>
  <FooterBar />
</template>

// src/app.tsx
import Header from "./components/Layout/header";
<<<<<<< HEAD
=======
import About from "./components/Sections/about";
import Stacks from "./components/Sections/stacks";
>>>>>>> a862d03 (feat: finish about section)

const App = () => {
	return (
		<>
			<Header />
<<<<<<< HEAD
			<main>
				<p>oi</p>
=======
			<main className="flex flex-col items-center !mt-16">
				<About />
				<Stacks />
>>>>>>> a862d03 (feat: finish about section)
			</main>
		</>
	);
};

export default App;
